In [1]:
import numpy as np

In [3]:
A = np.array([1,2,3,4])

In [4]:
A

array([1, 2, 3, 4])

In [6]:
B = np.array([[1,3,4,5],[2,3,4,5]])

In [7]:
B

array([[1, 3, 4, 5],
       [2, 3, 4, 5]])

using B.shape return (2,4) mean that 2 rows and 4 colums

In [8]:
B.shape

(2, 4)

Mathematical operation with data it like multipaltion of matrix

In [2]:
import numpy as np

In [6]:
data = np.array([[1,2,3,4],[2,3,4,6]])
data *10

array([[10, 20, 30, 40],
       [20, 30, 40, 60]])

In [8]:
data +data 

array([[ 2,  4,  6,  8],
       [ 4,  6,  8, 12]])


The easiest way to create an array is to use the array function.
 This accepts any sequence-like object (including other arrays) and produces a new NumPy array containing the passed data. For example, a list is a good candidate for conversion:

In [9]:
data1= [6,7.5,8,0,10 ]
arra1 = np.array(data1)


In [10]:
arra1

array([ 6. ,  7.5,  8. ,  0. , 10. ])

numpy.zeros and numpy.ones can create arrays of 0s or 1s 

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,6))


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.empty((2,3,2))


array([[[1.42137836e-076, 1.91087105e+137],
        [9.02193423e+217, 6.19941898e-071],
        [2.95150849e-075, 2.13412571e+257]],

       [[5.53177327e+228, 9.89803615e+164],
        [9.16281387e-072, 5.92863223e-114],
        [9.45956265e-076, 1.61410559e+132]]])

np.empty not return an array of all zeros, it may contain nonzero "garbage: values

numpy.arrange is an array-valued version of the built-in Python range function:

In [6]:
np.arange(15)
#Create an array with 15 elements,
#each having a value equal to its index

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

signed integers types can represent both positive and negative integers
unsigned integer can only represent nonzero integers

In [8]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [10]:
arr.astype(np.int64)

array([1, 2, 3, 4, 5], dtype=int64)

In [13]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')